import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
  return (
    <div className="flex items-center">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <span className = "flex items-center">
        <Link href="/moose-hide-landing" className="mx-auto animate-ping text-xl text-blue-600 uppercase font-bold">Moose Hide Landing Parks and Rec!</Link>
      </span>
    </div>
  )
}